import Treatments from '@/pages/treatments/Treatments'
import React from 'react'

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Best chiropractic :Dr. Rajneesh Kant",
  description: "Generated by create next app",
};
const Page = ({ params }: { params: { slug: string } }) => {

    return <Treatments slug={params?.slug} />
}

export default Page