import Profile from '@/pages/profile/profile'
import React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Profile:Dr. Rajneesh Kant",
  description: "Generated by create next app",
};

const Page = () => {
  return <Profile/>
}

export default Page