import AuthSystem from '@/pages/auth/Login'
import React from 'react'

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign in and Sign up at:Dr. Rajneesh Kant",
  description: "Generated by create next app",
};
const Login = () => {
  return <AuthSystem/>
}

export default Login 